# Generated by Django 3.1 on 2021-05-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField()),
                ('emailid', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('softwares', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('projects', models.TextField()),
                ('certification', models.CharField(max_length=100)),
                ('achievements', models.TextField()),
                ('strengths', models.CharField(max_length=100)),
                ('weakness', models.CharField(max_length=100)),
                ('schoolname', models.CharField(max_length=100)),
                ('schoolduration', models.IntegerField()),
                ('percentageofschoolmarks', models.IntegerField()),
                ('collegename', models.CharField(max_length=100)),
                ('collegeduration', models.IntegerField()),
                ('percentageofcollegemarks', models.IntegerField()),
                ('collegeuniversity', models.CharField(max_length=100)),
                ('languagesknown', models.TextField()),
            ],
        ),
    ]
